>XP_031708711.1 ubiquitin-like protein ATG12 [Anarrhichthys ocellatus]
MKMSD-----------------------------------------------NAES----
---------------PIETQK-----EES----QPPSDDSTTNDDKKKIDVLLKAVGDTP
IMKTKKWTMDRGRTVQSLSQFISRFLKLDGSEQL-----------------FIYVNQSFA
PSPDQDVGVLFDCFGSDGKLILHYCKSQAWG
>XP_031643127.1 ubiquitin-like protein ATG12 isoform X1 [Oncorhynchus kisutch]
--MSD-----------------------------------------------NAES----
---------------PTETQK-----DEPS-TPQQPTEDLGTADEKKKIDVLLKAVGDTP
IMKTKKWSVEKGRTVQSLSQFISRFLKMEANEQLLSSPCDMSGLPLLSVTEFIYVNQSFS
PSPDQEVGVLFECFGSDGKLVLHYCKSQAWG
>NP_001233129.1 ubiquitin-like protein ATG12 [Danio rerio]
--MSD-----------------------------------------------NAES----
---------------PTENPK-----DEHS-LQHAVTDHSESSDEKKKIDVLLKAVGVTP
IMKTKKWSVERRRTIQSLAQFISRFLKLEPSEQL-----------------FIYVNQSFA
PSPDQEVGVLFECFGSDGKLVLHYCKSQAWG
>XP_036824561.1 ubiquitin-like protein ATG12 [Oncorhynchus mykiss]
--MSD-----------------------------------------------NAES----
---------------PTETQK-----DEPS-TPQQPTEDSGMADDKKKIDVLLKAVGDTP
IMKTKKWSVEKGRTVQSLSQFISRFLKMEANEQL-----------------FIYVNQSFS
PSPDQEVGVLFECFGSDGKLVLHYCKSQAWG
>159-410_1 LIB3733-025-A1-K1-G4 LIB3733 Canis lupus familiaris cDNA clone CLN12919377, mRNA sequence
------------------------------------------------------------
------------------------------------------------IDVL*KDVGDTP
IMKTKKXXEERTQTIQGLIDFIKKFLKLVNSEQL-----------------FIYVNHSFA
PSTDQKNGTLYK*IISNIKL*LHYCKSNA--
>ACD74941.1 Atg12 [Homo sapiens]
--MTSREHQVSLCNCVPLLRRLLCDAPWRKARPLHALSRYFRSRVSPSKMAEEPQSVLQL
PTSIAAGGEGLTDVSPETTTP-----EPPSSAAVSPGTEEPAGDTKKKIDILLKAVGDTP
IMKTKKWAVERTRTIQGLIDFIKKFLKLVASEQL-----------------FIYVNQSFA
PSPDQEVGTLYECFGSDGKLVLHYCKSQAWG
>XP_042789380.1 ubiquitin-like protein ATG12 isoform X1 [Panthera leo]
--MAE-----------------------------------------------EPESALQL
PPSSTTDGEG-----PTEVSPETATPEPPSSAAVSPGTEEPAGDTKKKIDVLLKAVGDTP
IMKTKKWAVERTRTIQGLIDFIKKFLKLVASEQL-----------------FIYVNQSFA
PSPDQEVGTLYECFGSDGKLVLHYCKSQAWG
